data:
  repo: iterative/dvc

  labels:
  - data-sync
  - experiments
  - pipelines

  since: 2021/01/01
  until: 2022/04/01

  output_folder: outs/data
  metrics_file: outs/data_metrics.json

split:
  output_folder: outs/split
  metrics_file: outs/split_metrics.json
  test_size: 0.2

train:
  output_folder: outs/train
  metrics_folder: outs/train_metrics
  pretrained_model: MoritzLaurer/xtremedistil-l6-h256-mnli-fever-anli-ling-binary
  epochs: 2

eval:
  output_folder: outs/eval
